Mvc_5TicariOtamasyon/Models/sınıflar/cari.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Mvc_5TicariOtamasyon.Models.sınıflar
{
    public class cari
    {
        [Key]
        public int cariID { get; set; }
        [Column(TypeName = "Varchar")]

        [Display(Name = "Ad:")]

        [StringLength(30,ErrorMessage ="En fazla 30 karakter girebilirsiniz")]
        public string cariAd { get; set;}

        [Display(Name = "Soyad:")]
        [Column(TypeName = "Varchar")]

        [StringLength(30)]
        [Required(ErrorMessage ="Bu alanı boş geçemezsiniz")]
        public string cariSoyad { get; set;}

        [Display(Name = "Şehir:")]
        [Column(TypeName = "Varchar")]

        [StringLength(13)]

        public string cariSehir { get; set; }
        [Display(Name = "Mail:")]
        [Column(TypeName = "Varchar")]

        public string carimeslek { get; set; }
        [Display(Name = "Meslek:")]
        [Column(TypeName = "Varchar")]

        public string caritel { get; set; }
        [Display(Name = "Telefon:")]
        [Column(TypeName = "Varchar")]
        [StringLength(50)]
        public string cariMail { get; set; }

        [Display(Name = "Şifre:")]
        [Column(TypeName = "Varchar")]

        [StringLength(20)]
        public string cariSifre { get; set; }
        public bool durum { get; set; }

        public ICollection<satis_hareketi> satis_Hareketis { get; set; }

        //her cari birden birden fazla satış hareketi içerebilir
    }
}

Mvc_5TicariOtamasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc_5TicariOtamasyon.Models.sınıflar;

namespace Mvc_5TicariOtamasyon.Controllers
{
    public class CariController : Controller
    {
        // GET: Cari
        Context c=new Context();
        public ActionResult Index()
        {
            var degerler=c.caris.Where(x => x.durum ==true).ToList();
            return View("Index",degerler);
        }
        [HttpGet]
        public ActionResult CariEkle()
        {
          
            return View();
        }
        [HttpPost]
        public ActionResult CariEkle(cari x)
        {
           c.caris.Add(x);
            c.SaveChanges ();

            return RedirectToAction("Index");
        }

        public ActionResult CariSil(int id)
        {
            var carisil = c.caris.Find(id);
            carisil.durum = false;
            c.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult CariGetir(int id)
        {
            var cgetir=c.caris.Find(id);    
            return View("CariGetir", cgetir);
        }

        public ActionResult CariGuncelle(cari car)
        {

            if (!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var dgr = c.caris.Find(car.cariID);
            dgr.cariAd = car.cariAd;
            dgr.cariSoyad = car.cariSoyad;
            dgr.cariSehir = car.cariSehir;
            dgr.cariMail = car.cariMail;
            c.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult MüsteriSatis(int id)
        {
            var cr = c.caris.Where(x => x.cariID == id).Select(y => y.cariAd + " " + y.cariSoyad).FirstOrDefault();
            ViewBag.cari = cr;
            var degerlers = c.satis_Hareketis.Where(x => x.cariid == id).ToList();
            return View("MüsteriSatis", degerlers);

        }


        //eğer admin kısmında yetkiye göre bu sayfanın görünüp görünmeme durumunu göstermek istiyorsan csharedden adminlayouta git  ve if bloğu içine al o kısımı
    }
}

Mvc_5TicariOtamasyon/Views/Cari/CariEkle.cshtml
@model Mvc_5TicariOtamasyon.Models.sınıflar.cari
@{
    ViewBag.Title = "CariEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<br />
<h2>Cari Ekle</h2>
<br />
<form method="post" class="form-group" id="cariForm">
    @Html.LabelFor(x => x.cariAd)
    @Html.TextBoxFor(x => x.cariAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.cariSoyad)
    @Html.TextBoxFor(x => x.cariSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.cariSehir)
    @Html.TextBoxFor(x => x.cariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.cariMail)
    @Html.TextBoxFor(x => x.cariMail, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.durum)
    @Html.TextBoxFor(x => x.durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-default text-white" style="background-color:darkslateblue" id="btn1">Ekle</button>

    <script>
        $('#btn1').click(function (e) {
            e.preventDefault();

            swal({
                title: "Good Job!",
                text: "İşlem Başarılı!",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "Tamam",
                        value: true,
                        visible: true,
                        closeModal: true // Bildirimi otomatik kapatma
                    }
                }
            }).then((value) => {
                if (value) {
                    // Ekleme işlemini AJAX ile gerçekleştir
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("CariEkle", "Cari")', // ControllerName ve action adını uygun şekilde değiştirin
                        data: $('#cariForm').serialize(), // Form verilerini al
                        success: function (data) {
                            // İşlem başarılı olduğunda bu bölüm çalışır
                            // Burada gerekli yönlendirme veya diğer işlemleri yapabilirsiniz
                             window.location.href = '@Url.Action("Index", "Cari")'; // Yönlendirme için uygun URL'yi belirtin
                        }
                    });
                }
            });
        });
    </script>

</form>

Mvc_5TicariOtamasyon/Views/Cari/CariGetir.cshtml
@model Mvc_5TicariOtamasyon.Models.sınıflar.cari
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h2>Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("CariGuncelle", "Cari", FormMethod.Post))
{
    @Html.LabelFor(x => x.cariAd)
    @Html.TextBoxFor(x => x.cariAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.cariAd, "", new { @style = "color:red" }) //uyarı mesajı
    <br />
    @Html.LabelFor(x => x.cariSoyad)
    @Html.TextBoxFor(x => x.cariSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.cariSoyad, "", new { @style = "color:orange" }) //uyarı mesajı

    <br />
    @Html.LabelFor(x => x.cariSehir)
    @Html.TextBoxFor(x => x.cariSehir, new { @class = "form-control" })

    <br />
    @Html.LabelFor(x => x.cariMail)
    @Html.TextBoxFor(x => x.cariMail, new { @class = "form-control" })
    <br />

    @Html.HiddenFor(x => x.cariID)
    <br />
    <button class="btn btn-info mt-3">Güncelle</button>

}

Mvc_5TicariOtamasyon/Views/Cari/Index.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar
@model List<cari>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Cari Alanı</h2>

<br />

<table class="table table-striped">
    <tr>
        <th>Cari ID</th>
        <th>Cari Ad</th>
        <th>Cari Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Satış Geçmişi</th>
    </tr>

    @foreach (var c in Model)
    {
        <tr>
           <td>@c.cariID</td>
            <td>@c.cariAd</td>
            <td>@c.cariSoyad</td>
            <td>@c.cariSehir</td>
            <td>@c.cariMail</td>
            <td><a href="/Cari/CariSil/@c.cariID" class="btn btn-danger">Sil</a></td>
            <td><a href="/Cari/CariGetir/@c.cariID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Cari/MüsteriSatis/@c.cariID" class="btn btn-info">Satış Geçmişi</a></td>

        </tr>
    }



</table>

<a href="/Cari/CariEkle" class="btn btn-primary">Cari Ekle</a>

Mvc_5TicariOtamasyon/Views/Cari/MüsteriSatis.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar
@model List<satis_hareketi>
@{
    ViewBag.Title = "MüsteriSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2 class="fs-4">Müsteri  Satış Sayfası </h2>
<br />
<div class="bg-light py-3 px-2 " style="font:bold;font-weight:600;">
    Cari Ad:  @ViewBag.cari
</div>

<br />

<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.satisID</td>
            <td>@x.urun.urunAD</td>
            <td>@x.personel.PersonelAd @x.personel.PersonelSoyAD</td>
            <td>@x.fiyat</td>
            <td>@x.adet</td>
            <td>@x.toplamtutar</td>
            <td>@x.tarih</td>
            <td><a href="/Departman/DepartmanPersSatisYazdır/@x.satisID" class="btn btn-info">Yazdır</a></td>
        </tr>
    }

</table>