Mvc_5TicariOtamasyon/Controllers/GrafikController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Mvc_5TicariOtamasyon.Models.sınıflar;
namespace Mvc_5TicariOtamasyon.Controllers
{
    [Authorize]
    public class GrafikController : Controller
    {
        // GET: Grafik

        //aşağıdakiler biraz küt kalıyor daha kaliteli Chartlar kullnamak için paket yönetici Konsolundan
        //    Newtonsoft.Json eklentisini kur
        Context c = new Context();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Index2()
        {
            var grafik = new Chart(600, 600);
            grafik.AddTitle(text: "Kategori-Ürün Stok Sayısı");
            grafik.AddLegend(title: "Stok");
            grafik.AddSeries(
                name: "Değerler",
                xValue: new[] { "Beyaz Eşya", "Televizyon", "Bilgisayar" },
                yValues: new[] { 85, 65, 98 }

                ).Write();
            return File(grafik.ToWebImage().GetBytes(), "image/jpeg");
        }
        public ActionResult Index3()
        {
            ArrayList xvalue = new ArrayList();
            ArrayList yvalue = new ArrayList();

            var sonuc = c.uruns.ToList();
            sonuc.ToList().ForEach(x => xvalue.Add(x.urunAD));
            sonuc.ToList().ForEach(y => yvalue.Add(y.stock));

            var grafik = new Chart(600, 600);
            grafik.AddTitle(text: "Ürün/Stok İlişkisi");
            grafik.AddLegend(title: "Stok Sayısı");

            grafik.AddSeries(
                chartType: "Pie",
                name: "Stok Verileri",
                xValue: xvalue,
                yValues: yvalue

                ).Write();
            return View();
        }

        public ActionResult Index4()
        {
            return View();
        }
        public PartialViewResult deneme()
        {

            return PartialView();
        }
        //google chartlardaki görselleştirmeye ulaşabilmek için
        public ActionResult VisualizeUrunResult()
        {
            return Json(Urunlistesi(), JsonRequestBehavior.AllowGet);
        }
        //--------------DİNAMİK OLMAYAN KULLANIM ŞEKLE ELLE VERİLERİ GİRMEK
        public List<sinifgooglechart> Urunlistesi()
        {
            List<sinifgooglechart> nesne = new List<sinifgooglechart>();
            nesne.Add(new sinifgooglechart()
            {
                urunad = "Bilgisayar",
                stock = 120

            });

            nesne.Add(new sinifgooglechart()
            {
                urunad = "Telefon",
                stock = 80
            });

            nesne.Add(new sinifgooglechart()
            {
                urunad = "Kulaklık",
                stock = 60
            });

            nesne.Add(new sinifgooglechart()
            {
                urunad = "Beyaz Eşya",
                stock = 150
            });

            return nesne;
        }


        //-----DİNAMİK OLARAK VT DAN VERİ ÇEKME 

        public ActionResult Index5()
        {
            return View();
        }

        public ActionResult VisualizeUrunResult2()
        {

            return Json(Urunlistesi2(), JsonRequestBehavior.AllowGet);
        }

        public List<dinamikchart> Urunlistesi2()
        {
            List<dinamikchart> nesne= new List<dinamikchart>(); 
            using(var c=new Context())
            {
                nesne = c.uruns.Select(x => new dinamikchart()
                {
                    urnad=x.urunAD,
                    stk=x.stock
                }).ToList();
            }

            return nesne;
        }


        public PartialViewResult kategoriurun()
        {
            var sonuc1 = c.caris.ToList();

            // Verileri JavaScript tarafına taşı
            ViewBag.ChartData = sonuc1.GroupBy(x=>x.cariSehir).Select(group => new {sehir=group.Key ,adet=group.Count()}).ToList();

            return PartialView();
        }


        public PartialViewResult kategoriurun2()
        {
            var urunler = c.uruns.ToList();
            var kategoriler = c.kategoris.ToList();

            // Verileri JavaScript tarafına taşı
            var chartData = kategoriler
                .Select(kategori => new
                {
                    kateg = kategori.kategoriAD,
                    urun = urunler.Count(u => u.kategoriID == kategori.kategoriID)
                })
                .ToList();

            ViewBag.ChartData = chartData;


            return PartialView();
        }


        public ActionResult ColumnGrafik()
        {
            return View();
        }

        public ActionResult AreaGrafik()
        {
            return View();
        }



    }
}

Mvc_5TicariOtamasyon/Controllers/İstatistikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc_5TicariOtamasyon.Models.sınıflar;

namespace Mvc_5TicariOtamasyon.Controllers
{
    [Authorize]
    public class İstatistikController : Controller
    {
        // GET: İstatistik
        Context c = new Context();
        public ActionResult Index()
        {
            var deger1 = c.caris.Count().ToString();
            ViewBag.d1 = deger1;

            var deger2 = c.uruns.Count().ToString();
            ViewBag.d2 = deger2;

            var deger3 = c.personels.Count().ToString();
            ViewBag.d3 = deger3;

            var deger4 = c.kategoris.Count().ToString();
            ViewBag.d4 = deger4;

            var deger5 = c.uruns.Sum(x => x.stock).ToString();
            ViewBag.d5 = deger5;


            var deger6 = (from x in c.uruns select x.marka).Distinct().Count().ToString(); //Distinct tekrarsız
            ViewBag.d6 = deger6;

            var deger7 = c.uruns.Count(x => x.stock < 20).ToString();
            ViewBag.d7 = deger7;


            var deger8 = (from x in c.uruns select x.SatisFiyati).Max().ToString();
            ViewBag.d8 = deger8;

            var deger9 = (from x in c.uruns select x.SatisFiyati).Min().ToString();
            ViewBag.d9 = deger9;

            var deger12 = (from x in c.uruns select x.marka).Max().ToString();
            ViewBag.d12 = deger12;

            var deger10 = c.uruns.Count(x => x.urunAD == "Buzdolabı").ToString();
            ViewBag.d10 = deger10;

            var deger11 = c.uruns.Count(x => x.urunAD == "Laptop").ToString();
            ViewBag.d11 = deger11;

            var deger13 = c.uruns.Where(u => u.urunID == c.satis_Hareketis.GroupBy(a => a.urunid).OrderByDescending(x => x.Count()).Select(y => y.Key).FirstOrDefault()).Select(z => z.urunAD + " ").FirstOrDefault();
            ViewBag.d13 = deger13;


            var deger14 = c.satis_Hareketis.Sum(x => x.toplamtutar).ToString();
            ViewBag.d14 = deger14;

            var deger15 = c.satis_Hareketis.Count(x => x.tarih == DateTime.Today).ToString();
            ViewBag.d15 = deger15;


            var deger16 = c.satis_Hareketis.Where(x => x.tarih == DateTime.Today).Sum(x => (decimal?)x.toplamtutar).ToString();
            ViewBag.d16 = deger16; //(decimal?) eğer null döndürüyorsan hata fırlatma ((Nullable type))




            return View();
        }
        public ActionResult basictablolar()
        {
            var sorgu = from x in c.caris //cariler tablosunda çalışacağım x. ile carilerin tüm içeriğine ulaşabilirim
                        group x by x.cariSehir into g //grupla neye göre =x'e göre grupla  xin içindeki sehirler tarafından grupla ve g içine aktar. Bu satır, caris koleksiyonundaki öğeleri cariSehir özelliğine göre gruplar. g ise bu grupların her birini temsil eder.
                        select new grupsinif //: Bu bölüm, her bir grup için yeni bir nesne oluşturur.
                        {
                            sehir = g.Key,
                            sayi = g.Count()
                        };
            return View(sorgu.ToList());
        }
        public PartialViewResult Partial1()
        {
            var sorgu2 = from x in c.personels
                         group x by x.departman.departmanAD into g
                         select new grupsinif2
                         {
                             departman = g.Key,
                             sayi = g.Count()

                         };
            return PartialView(sorgu2.ToList());
        }

        public PartialViewResult Partial2()
        {
            var degerler = c.caris.ToList();
            return PartialView(degerler);


        }
        public PartialViewResult Partial3()
        {
            var degerler = c.uruns.ToList();
            return PartialView(degerler);
        }

        public PartialViewResult Partial4()
        {
            var sorgu = from x in c.uruns
                        group x by x.marka into g
                        select new grupsinif3
                        {
                            marka = g.Key,
                            sayi = g.Count()

                        };
            return PartialView(sorgu);
        }
        public PartialViewResult Partial5()
        {
            var sorgu = from x in c.uruns
                        group x by x.kategori.kategoriAD into g
                        select new grupsinif4
                        {
                          kategori=g.Key, sayi=g.Count()


                        };
            return PartialView(sorgu);
        }
    }
}

Mvc_5TicariOtamasyon/Views/Grafik/AreaGrafik.cshtml
@{
    ViewBag.Title = "AreaGrafik";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="font-italic mt-3 fs-4">Kategori/Ürün Çeşitliliği</h3>

@Html.Action("kategoriurun2", "Grafik")

Mvc_5TicariOtamasyon/Views/Grafik/ColumnGrafik.cshtml
@{
    ViewBag.Title = "ColumnGrafik";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3 class="font-italic mt-3 fs-4" >Cari/Şehir Grafiği</h3>

@Html.Action("kategoriurun","Grafik")

Mvc_5TicariOtamasyon/Views/Grafik/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

@*@{

        var grfk = new Chart(width: 500, height: 500);

        grfk.AddTitle(text: "Kategoriler ve Ürün Sayıları");
        grfk.AddLegend(title: "Değerler");
        grfk.AddSeries(
            name:"Veriler",
            //   chartType yazmazsak normal grafik formatında geliyor degerler  Pie=>Pasta dilimi Area=>Tepecikli bölge bar=>soldan çıkan
            chartType: "Pie",
            xValue: new[] {"Beyaz Eşya","Televizyon","Bilgisayar","Küçük Ev Aleti"},
            yValues: new[] {500,250,340,620}


            );


        grfk.Write();
    }*@
<br />
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                @Html.Action("kategoriurun", "Grafik")
                <!-- /.card -->
                <br /> <br />
                @*partial viewi Basictablolar viewin içine dahil etmiş oluyorum !!!!*@
                <!-- /.card -->
            </div>
            <!-- /.col -->
            <div class="col-md-6">

                <!-- /.card -->
                @Html.Action("Partial4", "İstatistik")
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

        @Html.Action("kategoriurun2", "Grafik")


        <!-- /.row -->
        @Html.Action("kategoriurun", "Grafik")
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

Mvc_5TicariOtamasyon/Views/Grafik/Index2.cshtml
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index2</h2>

<div style="width:600px;height:600px;">
    <img src="@Url.Action("Index2","Grafik")" alt="Alternate Text" />
</div>

Mvc_5TicariOtamasyon/Views/Grafik/Index3.cshtml
@{
    ViewBag.Title = "Index3";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(function () {
            drawChart(@Html.Raw(Json.Encode(ViewBag.ChartData))); // Verileri JavaScript nesnesine dönüştür
        });

        function drawChart(chartData) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');

            for (var i = 0; i < chartData.length; i++) {
                data.addRow([chartData[i].urnad, chartData[i].stock]);
            }

            var columnChartOptions = {
                title: "Ürün/Stok İlişkisi",
                titleTextStyle: {
                    fontSize: 18,
                    bold: true
                },
                titlePosition: 'left',
                width: 1200,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div" class="text-center"></div>


</body>
</html>

Mvc_5TicariOtamasyon/Views/Grafik/Index4.cshtml
@{
    ViewBag.Title = "Index4";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeUrunResult", "Grafik")',
                success: function (result) {
                    google.charts.load('current', { 'packages': ['corechart'] });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.urunad, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document.getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>
        <a href="@Url.Action("ColumnChart")" class="btn btn-primary">Column Chart</a>
        <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@
</body>
</html>

Mvc_5TicariOtamasyon/Views/Grafik/Index5.cshtml
@{
    ViewBag.Title = "Index5";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h3 class=" fs-4 mt-3 " style="font-size:initial"> Ürün/Stok Grafiği</h3>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>


        $(document).ready(function () {
            google.charts.load('current', { 'packages': ['corechart'] });
            google.charts.setOnLoadCallback(function () {
                // Sayfa yüklendiğinde ilk grafiği çiz
                drawDefaultChart();
            });
        });

        function drawDefaultChart() {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeUrunResult2", "Grafik")',
                success: function (result) {
                    var data = new google.visualization.DataTable();
                    data.addColumn('string', 'Name');
                    data.addColumn('number', 'Stoklar');
                    var dataArray = [];
                    $.each(result, function (i, obj) {
                        dataArray.push([obj.urnad, obj.stk]);
                    });
                    data.addRows(dataArray);

                    var chartOptions = {

                        titleTextStyle: {
                            fontSize: 18, // Başlık yazısının font boyutu (px cinsinden)
                            bold: true    // Kalın yazı
                        },
                        width: 1200,
                        height: 900,
                        bar: { groupWidth: "20%" },
                    };

                    var columnChart = new google.visualization.PieChart(document.getElementById('chart_div'));
                    columnChart.draw(data, chartOptions);



                }
            });
        }
    </script>
</head>
<body>
    <div id="chart_div" class="text-center"></div>




</body>
</html>

Mvc_5TicariOtamasyon/Views/Grafik/deneme.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeUrunResult", "Grafik")',
                success: function (result) {
                    google.charts.load('current', { 'packages': ['corechart'] });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];
            $.each(result, function (i, obj) {
                dataArray.push([obj.urunad, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün Stok Grafiği",
                titleTextStyle: {
                    fontSize: 18, // Başlık yazısının font boyutu (px cinsinden)
                    bold: true    // Kalın yazı
                },
                titlePosition: 'left',
                width: 1200,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_div'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_div" class="text-center"></div>
    @*<a href="@Url.Action("PieChart")" class="btn btn-danger">Pie Chart</a>
        <a href="@Url.Action("ColumnChart")" class="btn btn-primary">Column Chart</a>
        <a href="@Url.Action("LineChart")" class="btn btn-warning">Line Chart</a>*@
</body>
</html>

Mvc_5TicariOtamasyon/Views/Grafik/kategoriurun.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(function () {
            drawChart(@Html.Raw(Json.Encode(ViewBag.ChartData))); // Verileri JavaScript nesnesine dönüştür
        });

        function drawChart(chartData) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Şehirler');

            for (var i = 0; i < chartData.length; i++) {
                data.addRow([chartData[i].sehir, chartData[i].adet]);
            }

            var columnChartOptions = {
              
                titleTextStyle: {
                    fontSize: 18,
                    bold: true
                },
                titlePosition: 'right',
                width: 1200,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document.getElementById('columnchart_divvv'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="columnchart_divvv" class="text-center" style="display:inline-block"></div>
</body>
</html>

Mvc_5TicariOtamasyon/Views/Grafik/kategoriurun2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://www.gstatic.com/charts/loader.js"></script>
    <script>
        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(function () {
            drawChart(@Html.Raw(Json.Encode(ViewBag.ChartData))); // Verileri JavaScript nesnesine dönüştür
        });

        function drawChart(chartData) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Kategoriler');

            for (var i = 0; i < chartData.length; i++) {
                data.addRow([chartData[i].kateg, chartData[i].urun]);
            }

            var columnChartOptions = {
       
                titleTextStyle: {
                    fontSize: 18,
                    bold: true
                },
                titlePosition: 'right',
                width: 1200,
                height: 700,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.AreaChart(document.getElementById('chart_div1'));
            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="chart_div1" class="text-center"></div>


   
</body>
</html>