Mvc_5TicariOtamasyon/Models/sınıflar/departman.cs
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

    namespace Mvc_5TicariOtamasyon.Models.sınıflar
    {
        public class departman
        {
            [Key]
            public int departmanID { get; set; }
        [Column(TypeName = "Varchar")]

        [StringLength(30)]


        public string departmanAD { get; set; }
        public bool durum { get; set; }

        //her personelin birden fazla departmanı olabilir

        public ICollection<personel> personels { get; set; }
    }
    }

Mvc_5TicariOtamasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mvc_5TicariOtamasyon.Models.sınıflar;

namespace Mvc_5TicariOtamasyon.Controllers
{
    [Authorize] //böyllikle her actionun üzerine eklemeye gerek kalmadı
    public class DepartmanController : Controller
    {
        // GET: Departman

        Context c=new Context();
      
        public ActionResult Index()
        {
            var degerler=c.departmans.Where(x=>x.durum==true).ToList();
            return View(degerler);
        }

        //Yetkilendirme beşinci adım  roller  klasörünün içndeki sınıfta yer alıyor diğer adımlar 
        [Authorize(Roles ="A")] //Yetkisi A olan sadece bu kısma giriş yapabilsin
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DepartmanEkle(departman d)
        {
            c.departmans.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanSil(int id)
        {
            var dep = c.departmans.Find(id);
            dep.durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanGetir(int id)
        {
            var depgtr = c.departmans.Find(id);
            return View("DepartmanGetir", depgtr);

            


        }

        public ActionResult DepartmanGuncelle(departman d)
        {
            var depart = c.departmans.Find(d.departmanID);
            depart.departmanAD = d.departmanAD;
            c.SaveChanges();    
            return RedirectToAction("Index");




        }

        public ActionResult DepartmanDetay(int id)
        {
            var pers=c.personels.Where(x=>x.departmanid==id).ToList();
            var dep=c.departmans.Where(x=>x.departmanID==id).Select(y=>y.departmanAD).FirstOrDefault();//sadece tek değeri taşıma işlemlerinde kullanılır
            ViewBag.d = dep;//controller tarafından çektiğimiz veriyi view sayfasına taşır
            return View("DepartmanDetay", pers);




        }

        public ActionResult DepartmanPersonelSatis(int id)

        {
            var degerler=c.satis_Hareketis.Where(x=>x.personelid==id).ToList();
            var dps=c.personels.Where(x=>x.PersonelID==id).Select(y=>y.PersonelAd +" "+  y.PersonelSoyAD).FirstOrDefault();
            ViewBag.dpersonel=dps;
            return View(degerler);

        }

        public ActionResult DepartmanPersSatisYazdır(int id)
        {
            var degerler = c.satis_Hareketis.Where(x => x.satisID == id).ToList();
            return View(degerler);
        }
    }
}

Mvc_5TicariOtamasyon/Views/Departman/DepartmanDetay.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar
@model List<personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2 class="fs-4">Departman Detay Sayfası </h2>
<br />
<div class="bg-light py-3 px-2 " style="font:bold;font-weight:600;">
    Departman Ad:  @ViewBag.d
</div>
<br />
<table class="table table-hover">
    <tr>
      
        <th>Ad Soyad</th>
      

        <th>SATIŞLAR</th>
    </tr>
    @foreach (var i in Model)
    {
    <tr>
    
        <td>@i.PersonelAd @i.PersonelSoyAD</td>
      
    
        <td><a href="/Departman/DepartmanPersonelSatis/@i.PersonelID" class="btn btn-dark">Satışlar</a></td>

    </tr>
    }
</table>

Mvc_5TicariOtamasyon/Views/Departman/DepartmanEkle.cshtml
@model Mvc_5TicariOtamasyon.Models.sınıflar.departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<br />
<h2>Departman Ekle</h2>
<br />

<form method="post" class="form-group" id="cariForm">

    @Html.LabelFor(x => x.departmanAD)
    @Html.TextBoxFor(x => x.departmanAD, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.durum)
    @Html.TextBoxFor(x => x.durum, new { @class = "form-control" })
    <button class="btn btn-primary mt-3" id="btn1">Ekle</button>

    <script>
        $('#btn1').click(function (e) {
            e.preventDefault();

            swal({
                title: "Good Job!",
                text: "İşlem Başarılı!",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "Tamam",
                        value: true,
                        visible: true,
                        closeModal: true // Bildirimi otomatik kapatma
                    }
                }
            }).then((value) => {
                if (value) {
                    // Ekleme işlemini AJAX ile gerçekleştir
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("DepartmanEkle", "Departman")', // ControllerName ve action adını uygun şekilde değiştirin
                        data: $('#cariForm').serialize(), // Form verilerini al
                        success: function (data) {
                            // İşlem başarılı olduğunda bu bölüm çalışır
                            // Burada gerekli yönlendirme veya diğer işlemleri yapabilirsiniz
                             window.location.href = '@Url.Action("Index", "Departman")'; // Yönlendirme için uygun URL'yi belirtin
                        }
                    });
                }
            });
        });
    </script>
</form>

Mvc_5TicariOtamasyon/Views/Departman/DepartmanGetir.cshtml
@model Mvc_5TicariOtamasyon.Models.sınıflar.departman

@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Güncelleme Sayfası</h2>
<br />

@using (Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post)) //bu sayfa yüklendikten sonra post işlemi  gerçekleştirdiğimde hangi ActionResult işlemi çalışacak
                                                                        //KategoriGuncelle isminde ActionResult tanımladım  Kategori controllerin içinde FormMethod.Post olduğunda çalışacak
{
    <div class="form-group ">
        @Html.LabelFor(x =>x.departmanAD )
        @Html.TextBoxFor(x => x.departmanAD, new { @class = "form-control mt-1 " })
        @Html.HiddenFor(x => x.departmanID)
        <button class="btn btn-info mt-3">Güncelle</button>
    </div>


}

Mvc_5TicariOtamasyon/Views/Departman/DepartmanPersSatisYazdır.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar

@model List<satis_hareketi>

@{

    Layout = null;

}

<br />

<!DOCTYPE html>

<html lang="tr">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>
                <th>Satış ID</th>
                <th>Ürün</th>
                <th>Cari</th>
                <th>Personel</th>
                <th>Fiyat</th>
                <th>Adet</th>
                <th>Toplam</th>
                <th>Tarih</th>
              
            </tr>

        </thead>

        <tbody>

            @foreach (var x in Model)

            {

                <tr>

                    <td>@x.satisID</td>

                    <td>@x.urun.urunAD</td>

                    <td>@x.cari.cariAd @x.cari.cariSoyad</td>
                    <td>@x.personel.PersonelAd @x.personel.PersonelSoyAD</td>

                    <td>@x.fiyat</td>

                    <td>@x.adet</td>

                    <td>@x.toplamtutar</td>

                    <td>@x.tarih</td>

               

                </tr>

            }



        </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

$(document).ready(function() {

    var table = $('#example').DataTable( {

        lengthChange: false,

        buttons: [ 'copy', 'excel', 'csv', 'pdf', 'colvis' ]

    } );



    table.buttons().container()

        .appendTo( '#example_wrapper .col-md-6:eq(0)' );

} );

    </script>

</body>

</html>

Mvc_5TicariOtamasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar
@model List<satis_hareketi>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2 class="fs-4">Departman Personel Satış Sayfası </h2>
<br />
<div class="bg-light py-3 px-2 " style="font:bold;font-weight:600;">
    Personel Ad:  @ViewBag.dpersonel
</div>

<br />

<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Cari</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.satisID</td>
            <td>@x.urun.urunAD</td>
            <td>@x.cari.cariAd @x.cari.cariSoyad</td>
            <td>@x.fiyat</td>
            <td>@x.adet</td>
            <td>@x.toplamtutar</td>
            <td>@Convert.ToDateTime(x.tarih).ToString("dd/MM/yyyy")</td>
            <td><a href="/Departman/DepartmanPersSatisYazdır/@x.satisID" class="btn btn-info">Yazdır</a></td>
        </tr>
            }
       
    </table>

Mvc_5TicariOtamasyon/Views/Departman/Index.cshtml
@using Mvc_5TicariOtamasyon.Models.sınıflar
@model  List<departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<br />
<h2>Departman Alanı</h2>

<br />

<table class="table table-bordered table-hover" style="margin-top: 20px; ">
    <tr class=" text-white table-dark">
     
        <th>DEPARTMAN AD</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
        <th> Detaylar</th>


    </tr>

    @foreach (var d in Model)
    {
        <tr>
          
            <td>@d.departmanAD</td>
         
            <td><a href="/Departman/DepartmanSil/@d.departmanID" class="btn btn-danger">SİL</a></td>
            <td><a href="/Departman/DepartmanGetir/@d.departmanID" class="btn btn-success">GÜNCELLE</a></td>
            <td><a href="/Departman/DepartmanDetay/@d.departmanID" class="btn btn-warning"> Detaylar</a></td>
        </tr>


    }
</table>
<a href="/Departman/DepartmanEkle" class="btn btn-primary">Departman Ekle</a>